# Generated by Django 4.2.7 on 2023-11-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hos_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=50)),
                ('location', models.TextField(max_length=100)),
                ('hos_site', models.CharField(max_length=50)),
            ],
        ),
    ]
