# Generated by Django 4.2.7 on 2023-11-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driv_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=30)),
                ('phone_num', models.IntegerField()),
                ('vehicle_num', models.IntegerField()),
                ('amb_type', models.CharField(max_length=30)),
                ('amb_status', models.CharField(max_length=30)),
            ],
        ),
    ]
