# Generated by Django 4.2.7 on 2023-11-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_driv_prof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='vehicle_num',
            field=models.CharField(max_length=10),
        ),
    ]
