# Generated by Django 4.2.7 on 2023-11-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_driv_prof_phone_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
