# Generated by Django 4.2.7 on 2023-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_driv_prof_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driv_prof',
            old_name='password',
            new_name='alternate_phone_number',
        ),
        migrations.RemoveField(
            model_name='driv_prof',
            name='username',
        ),
        migrations.AddField(
            model_name='driv_prof',
            name='ambulance_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='driv_prof',
            name='description',
            field=models.CharField(default='Whether your ambulance is registered under specific hospital or privately owned', max_length=30),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='amb_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='amb_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='place',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='vehicle_num',
            field=models.CharField(max_length=30),
        ),
    ]
