# Generated by Django 4.2.7 on 2023-12-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_password_driv_prof_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(default='Abhi(Default)', max_length=100, null=True),
        ),
    ]
