# Generated by Django 4.2.7 on 2023-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_driv_prof_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='description',
            field=models.CharField(default='Whether your ambulance is registered under specific hospital or privately owned', max_length=200),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
