# Generated by Django 4.2.7 on 2023-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_driv_prof_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(default='Name', max_length=100, null=True),
        ),
    ]
