# Generated by Django 4.2.7 on 2023-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_driv_prof_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='ambulance_image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
    ]
