# Generated by Django 4.2.7 on 2023-12-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_driv_prof_ambulance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(default='John Doe(Default)', max_length=100, null=True),
        ),
    ]
