# Generated by Django 4.2.7 on 2023-12-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_driv_prof_ambulance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='ambulance_image',
            field=models.ImageField(default='media/ambu.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='description',
            field=models.CharField(default='My ambulance is registered under XYZ hospital or privately owned', max_length=200),
        ),
    ]
