# Generated by Django 4.2.7 on 2023-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_driv_prof_ambulance_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driv_prof',
            name='lat',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.AddField(
            model_name='driv_prof',
            name='lon',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
