# Generated by Django 4.2.7 on 2023-12-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_driv_prof_lat_remove_driv_prof_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
            ],
        ),
    ]
