# Generated by Django 4.2.7 on 2023-12-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='lat',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='bookings',
            name='lon',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
