# Generated by Django 4.2.7 on 2023-12-06 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0017_bookings_lat_bookings_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='lon',
        ),
        migrations.AddField(
            model_name='bookings',
            name='ulat',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='ulon',
            field=models.FloatField(default='0'),
        ),
        migrations.CreateModel(
            name='Driv_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlat', models.FloatField()),
                ('dlon', models.FloatField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
