# Generated by Django 4.2.7 on 2023-12-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_driv_prof_dlat_driv_prof_dlon_alter_bookings_ulat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='ulat',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='ulon',
        ),
    ]
