# Generated by Django 4.2.7 on 2023-12-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_bookings_latitude_bookings_longitude_delete_driv_loc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driv_prof',
            name='latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='driv_prof',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
    ]
