# Generated by Django 4.2.7 on 2023-12-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_bookings_latitude_remove_bookings_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='latitude',
            field=models.FloatField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='longitude',
            field=models.FloatField(default='0', null=True),
        ),
    ]
