# Generated by Django 4.2.7 on 2023-12-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_driv_prof_latitude_alter_driv_prof_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
