# Generated by Django 4.2.7 on 2023-12-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_driv_prof_latitude_alter_driv_prof_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
