# Generated by Django 4.2.7 on 2023-12-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Booking_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
