# Generated by Django 4.2.7 on 2023-12-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_bookingrequests_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequests',
            name='Booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingrequests',
            name='Driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driv_prof'),
        ),
    ]
