# Generated by Django 4.2.7 on 2023-12-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_bookingrequests_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequests',
            old_name='Driver_name',
            new_name='first_name',
        ),
    ]
