# Generated by Django 4.2.7 on 2023-12-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_bookingrequests_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingRequests',
        ),
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
