# Generated by Django 4.2.7 on 2023-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_bookingrequests_alter_driv_prof_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
    ]
