# Generated by Django 4.2.7 on 2023-12-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_driv_prof_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='first_name',
            field=models.CharField(default='John Doe(Default)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BookingRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Booking_date', models.DateField(auto_now_add=True)),
                ('Driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driv_prof')),
            ],
        ),
    ]
