# Generated by Django 4.2.7 on 2023-12-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_driv_prof_first_name_bookingrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingrequests',
            old_name='first_name',
            new_name='phone_num',
        ),
    ]
