# Generated by Django 4.2.7 on 2023-12-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_rename_first_name_bookingrequests_phone_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='location',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='bookingrequests',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
