# Generated by Django 4.2.7 on 2023-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_driv_prof_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driv_prof',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
