# Generated by Django 4.2.7 on 2023-12-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_remove_bookings_driver_remove_bookings_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitals',
            old_name='place',
            new_name='location',
        ),
    ]
